module.exports = [{
  "station_nm": "가능",
  "line_num": "1",
  "station_cd": "1907"
}, {
  "station_nm": "가산디지털단지",
  "line_num": "1",
  "station_cd": "1702"
}, {
  "station_nm": "간석",
  "line_num": "1",
  "station_cd": "1816"
}, {
  "station_nm": "개봉",
  "line_num": "1",
  "station_cd": "1801"
}, {
  "station_nm": "관악",
  "line_num": "1",
  "station_cd": "1705"
}, {
  "station_nm": "광명",
  "line_num": "1",
  "station_cd": "1750"
}, {
  "station_nm": "광운대",
  "line_num": "1",
  "station_cd": "1019"
}, {
  "station_nm": "구로",
  "line_num": "1",
  "station_cd": "1701"
}, {
  "station_nm": "구일",
  "line_num": "1",
  "station_cd": "1813"
}, {
  "station_nm": "군포",
  "line_num": "1",
  "station_cd": "1709"
}, {
  "station_nm": "금정",
  "line_num": "1",
  "station_cd": "1708"
}, {
  "station_nm": "금천구청",
  "line_num": "1",
  "station_cd": "1703"
}, {
  "station_nm": "남영",
  "line_num": "1",
  "station_cd": "1002"
}, {
  "station_nm": "노량진",
  "line_num": "1",
  "station_cd": "1004"
}, {
  "station_nm": "녹양",
  "line_num": "1",
  "station_cd": "1908"
}, {
  "station_nm": "녹천",
  "line_num": "1",
  "station_cd": "1021"
}, {
  "station_nm": "당정",
  "line_num": "1",
  "station_cd": "1729"
}, {
  "station_nm": "대방",
  "line_num": "1",
  "station_cd": "1005"
}, {
  "station_nm": "덕계",
  "line_num": "1",
  "station_cd": "1910"
}, {
  "station_nm": "덕정",
  "line_num": "1",
  "station_cd": "1911"
}, {
  "station_nm": "도봉",
  "line_num": "1",
  "station_cd": "1902"
}, {
  "station_nm": "도봉산",
  "line_num": "1",
  "station_cd": "1903"
}, {
  "station_nm": "도원",
  "line_num": "1",
  "station_cd": "1817"
}, {
  "station_nm": "도화",
  "line_num": "1",
  "station_cd": "1823"
}, {
  "station_nm": "독산",
  "line_num": "1",
  "station_cd": "1714"
}, {
  "station_nm": "동대문",
  "line_num": "1",
  "station_cd": "0155"
}, {
  "station_nm": "동두천",
  "line_num": "1",
  "station_cd": "1915"
}, {
  "station_nm": "동두천중앙",
  "line_num": "1",
  "station_cd": "1913"
}, {
  "station_nm": "동묘앞",
  "line_num": "1",
  "station_cd": "0159"
}, {
  "station_nm": "동암",
  "line_num": "1",
  "station_cd": "1808"
}, {
  "station_nm": "동인천",
  "line_num": "1",
  "station_cd": "1811"
}, {
  "station_nm": "두정",
  "line_num": "1",
  "station_cd": "1727"
}, {
  "station_nm": "망월사",
  "line_num": "1",
  "station_cd": "1904"
}, {
  "station_nm": "명학",
  "line_num": "1",
  "station_cd": "1707"
}, {
  "station_nm": "방학",
  "line_num": "1",
  "station_cd": "1901"
}, {
  "station_nm": "배방",
  "line_num": "1",
  "station_cd": "1405"
}, {
  "station_nm": "백운",
  "line_num": "1",
  "station_cd": "1807"
}, {
  "station_nm": "병점",
  "line_num": "1",
  "station_cd": "1716"
}, {
  "station_nm": "보산",
  "line_num": "1",
  "station_cd": "1914"
}, {
  "station_nm": "봉명",
  "line_num": "1",
  "station_cd": "1401"
}, {
  "station_nm": "부개",
  "line_num": "1",
  "station_cd": "1815"
}, {
  "station_nm": "부천",
  "line_num": "1",
  "station_cd": "1804"
}, {
  "station_nm": "부평",
  "line_num": "1",
  "station_cd": "1806"
}, {
  "station_nm": "서동탄",
  "line_num": "1",
  "station_cd": "1749"
}, {
  "station_nm": "서울",
  "line_num": "1",
  "station_cd": "0150"
}, {
  "station_nm": "서정리",
  "line_num": "1",
  "station_cd": "1722"
}, {
  "station_nm": "석계",
  "line_num": "1",
  "station_cd": "1018"
}, {
  "station_nm": "석수",
  "line_num": "1",
  "station_cd": "1704"
}, {
  "station_nm": "성균관대",
  "line_num": "1",
  "station_cd": "1711"
}, {
  "station_nm": "성환",
  "line_num": "1",
  "station_cd": "1725"
}, {
  "station_nm": "세류",
  "line_num": "1",
  "station_cd": "1715"
}, {
  "station_nm": "세마",
  "line_num": "1",
  "station_cd": "1717"
}, {
  "station_nm": "소사",
  "line_num": "1",
  "station_cd": "1814"
}, {
  "station_nm": "소요산",
  "line_num": "1",
  "station_cd": "1916"
}, {
  "station_nm": "송내",
  "line_num": "1",
  "station_cd": "1805"
}, {
  "station_nm": "송탄",
  "line_num": "1",
  "station_cd": "1721"
}, {
  "station_nm": "수원",
  "line_num": "1",
  "station_cd": "1713"
}, {
  "station_nm": "시청",
  "line_num": "1",
  "station_cd": "0151"
}, {
  "station_nm": "신길",
  "line_num": "1",
  "station_cd": "1032"
}, {
  "station_nm": "신도림",
  "line_num": "1",
  "station_cd": "1007"
}, {
  "station_nm": "신설동",
  "line_num": "1",
  "station_cd": "0156"
}, {
  "station_nm": "신이문",
  "line_num": "1",
  "station_cd": "1017"
}, {
  "station_nm": "신창",
  "line_num": "1",
  "station_cd": "1408"
}, {
  "station_nm": "쌍용(나사렛대)",
  "line_num": "1",
  "station_cd": "1402"
}, {
  "station_nm": "아산",
  "line_num": "1",
  "station_cd": "1403"
}, {
  "station_nm": "안양",
  "line_num": "1",
  "station_cd": "1706"
}, {
  "station_nm": "양주",
  "line_num": "1",
  "station_cd": "1909"
}, {
  "station_nm": "역곡",
  "line_num": "1",
  "station_cd": "1803"
}, {
  "station_nm": "영등포",
  "line_num": "1",
  "station_cd": "1006"
}, {
  "station_nm": "오류동",
  "line_num": "1",
  "station_cd": "1802"
}, {
  "station_nm": "오산",
  "line_num": "1",
  "station_cd": "1719"
}, {
  "station_nm": "오산대",
  "line_num": "1",
  "station_cd": "1718"
}, {
  "station_nm": "온수",
  "line_num": "1",
  "station_cd": "1821"
}, {
  "station_nm": "온양온천",
  "line_num": "1",
  "station_cd": "1407"
}, {
  "station_nm": "외대앞",
  "line_num": "1",
  "station_cd": "1016"
}, {
  "station_nm": "용산",
  "line_num": "1",
  "station_cd": "1003"
}, {
  "station_nm": "월계",
  "line_num": "1",
  "station_cd": "1020"
}, {
  "station_nm": "의왕",
  "line_num": "1",
  "station_cd": "1710"
}, {
  "station_nm": "의정부",
  "line_num": "1",
  "station_cd": "1906"
}, {
  "station_nm": "인천",
  "line_num": "1",
  "station_cd": "1812"
}, {
  "station_nm": "제기동",
  "line_num": "1",
  "station_cd": "0157"
}, {
  "station_nm": "제물포",
  "line_num": "1",
  "station_cd": "1810"
}, {
  "station_nm": "종각",
  "line_num": "1",
  "station_cd": "0152"
}, {
  "station_nm": "종로3가",
  "line_num": "1",
  "station_cd": "0153"
}, {
  "station_nm": "종로5가",
  "line_num": "1",
  "station_cd": "0154"
}, {
  "station_nm": "주안",
  "line_num": "1",
  "station_cd": "1809"
}, {
  "station_nm": "중동",
  "line_num": "1",
  "station_cd": "1822"
}, {
  "station_nm": "지제",
  "line_num": "1",
  "station_cd": "1723"
}, {
  "station_nm": "지행",
  "line_num": "1",
  "station_cd": "1912"
}, {
  "station_nm": "직산",
  "line_num": "1",
  "station_cd": "1726"
}, {
  "station_nm": "진위",
  "line_num": "1",
  "station_cd": "1720"
}, {
  "station_nm": "창동",
  "line_num": "1",
  "station_cd": "1022"
}, {
  "station_nm": "천안",
  "line_num": "1",
  "station_cd": "1728"
}, {
  "station_nm": "청량리",
  "line_num": "1",
  "station_cd": "0158"
}, {
  "station_nm": "평택",
  "line_num": "1",
  "station_cd": "1724"
}, {
  "station_nm": "화서",
  "line_num": "1",
  "station_cd": "1712"
}, {
  "station_nm": "회기",
  "line_num": "1",
  "station_cd": "1015"
}, {
  "station_nm": "회룡",
  "line_num": "1",
  "station_cd": "1905"
}, {
  "station_nm": "강남",
  "line_num": "2",
  "station_cd": "0222"
}, {
  "station_nm": "강변",
  "line_num": "2",
  "station_cd": "0214"
}, {
  "station_nm": "건대입구",
  "line_num": "2",
  "station_cd": "0212"
}, {
  "station_nm": "교대",
  "line_num": "2",
  "station_cd": "0223"
}, {
  "station_nm": "구로디지털단지",
  "line_num": "2",
  "station_cd": "0232"
}, {
  "station_nm": "구의",
  "line_num": "2",
  "station_cd": "0213"
}, {
  "station_nm": "까치산",
  "line_num": "2",
  "station_cd": "0200"
}, {
  "station_nm": "낙성대",
  "line_num": "2",
  "station_cd": "0227"
}, {
  "station_nm": "당산",
  "line_num": "2",
  "station_cd": "0237"
}, {
  "station_nm": "대림",
  "line_num": "2",
  "station_cd": "0233"
}, {
  "station_nm": "도림천",
  "line_num": "2",
  "station_cd": "0247"
}, {
  "station_nm": "동대문역사문화공원",
  "line_num": "2",
  "station_cd": "0205"
}, {
  "station_nm": "뚝섬",
  "line_num": "2",
  "station_cd": "0210"
}, {
  "station_nm": "문래",
  "line_num": "2",
  "station_cd": "0235"
}, {
  "station_nm": "방배",
  "line_num": "2",
  "station_cd": "0225"
}, {
  "station_nm": "봉천",
  "line_num": "2",
  "station_cd": "0229"
}, {
  "station_nm": "사당",
  "line_num": "2",
  "station_cd": "0226"
}, {
  "station_nm": "삼성",
  "line_num": "2",
  "station_cd": "0219"
}, {
  "station_nm": "삼전",
  "line_num": "2",
  "station_cd": "0219"
}, {
  "station_nm": "상왕십리",
  "line_num": "2",
  "station_cd": "0207"
}, {
  "station_nm": "서울대입구",
  "line_num": "2",
  "station_cd": "0228"
}, {
  "station_nm": "서초",
  "line_num": "2",
  "station_cd": "0224"
}, {
  "station_nm": "선릉",
  "line_num": "2",
  "station_cd": "0220"
}, {
  "station_nm": "성수",
  "line_num": "2",
  "station_cd": "0211"
}, {
  "station_nm": "시청",
  "line_num": "2",
  "station_cd": "0201"
}, {
  "station_nm": "신답",
  "line_num": "2",
  "station_cd": "0245"
}, {
  "station_nm": "신당",
  "line_num": "2",
  "station_cd": "0206"
}, {
  "station_nm": "신대방",
  "line_num": "2",
  "station_cd": "0231"
}, {
  "station_nm": "신도림",
  "line_num": "2",
  "station_cd": "0234"
}, {
  "station_nm": "신림",
  "line_num": "2",
  "station_cd": "0230"
}, {
  "station_nm": "신설동",
  "line_num": "2",
  "station_cd": "0246"
}, {
  "station_nm": "신정네거리",
  "line_num": "2",
  "station_cd": "0249"
}, {
  "station_nm": "신촌",
  "line_num": "2",
  "station_cd": "0240"
}, {
  "station_nm": "아현",
  "line_num": "2",
  "station_cd": "0242"
}, {
  "station_nm": "양천구청",
  "line_num": "2",
  "station_cd": "0248"
}, {
  "station_nm": "역삼",
  "line_num": "2",
  "station_cd": "0221"
}, {
  "station_nm": "영등포구청",
  "line_num": "2",
  "station_cd": "0236"
}, {
  "station_nm": "왕십리",
  "line_num": "2",
  "station_cd": "0208"
}, {
  "station_nm": "용답",
  "line_num": "2",
  "station_cd": "0244"
}, {
  "station_nm": "용두",
  "line_num": "2",
  "station_cd": "0250"
}, {
  "station_nm": "을지로3가",
  "line_num": "2",
  "station_cd": "0203"
}, {
  "station_nm": "을지로4가",
  "line_num": "2",
  "station_cd": "0204"
}, {
  "station_nm": "을지로입구",
  "line_num": "2",
  "station_cd": "0202"
}, {
  "station_nm": "이대",
  "line_num": "2",
  "station_cd": "0241"
}, {
  "station_nm": "잠실",
  "line_num": "2",
  "station_cd": "0216"
}, {
  "station_nm": "잠실나루",
  "line_num": "2",
  "station_cd": "0215"
}, {
  "station_nm": "잠실새내",
  "line_num": "2",
  "station_cd": "0217"
}, {
  "station_nm": "종합운동장",
  "line_num": "2",
  "station_cd": "0218"
}, {
  "station_nm": "충정로",
  "line_num": "2",
  "station_cd": "0243"
}, {
  "station_nm": "한양대",
  "line_num": "2",
  "station_cd": "0209"
}, {
  "station_nm": "합정",
  "line_num": "2",
  "station_cd": "0238"
}, {
  "station_nm": "홍대입구",
  "line_num": "2",
  "station_cd": "0239"
}, {
  "station_nm": "가락시장",
  "line_num": "3",
  "station_cd": "0340"
}, {
  "station_nm": "경복궁",
  "line_num": "3",
  "station_cd": "0317"
}, {
  "station_nm": "경찰병원",
  "line_num": "3",
  "station_cd": "0341"
}, {
  "station_nm": "고속터미널",
  "line_num": "3",
  "station_cd": "0329"
}, {
  "station_nm": "교대",
  "line_num": "3",
  "station_cd": "0330"
}, {
  "station_nm": "구파발",
  "line_num": "3",
  "station_cd": "0310"
}, {
  "station_nm": "금호",
  "line_num": "3",
  "station_cd": "0324"
}, {
  "station_nm": "남부터미널",
  "line_num": "3",
  "station_cd": "0331"
}, {
  "station_nm": "녹번",
  "line_num": "3",
  "station_cd": "0313"
}, {
  "station_nm": "대곡",
  "line_num": "3",
  "station_cd": "1953"
}, {
  "station_nm": "대청",
  "line_num": "3",
  "station_cd": "0337"
}, {
  "station_nm": "대치",
  "line_num": "3",
  "station_cd": "0335"
}, {
  "station_nm": "대화",
  "line_num": "3",
  "station_cd": "1958"
}, {
  "station_nm": "도곡",
  "line_num": "3",
  "station_cd": "0334"
}, {
  "station_nm": "독립문",
  "line_num": "3",
  "station_cd": "0316"
}, {
  "station_nm": "동대입구",
  "line_num": "3",
  "station_cd": "0322"
}, {
  "station_nm": "마두",
  "line_num": "3",
  "station_cd": "1955"
}, {
  "station_nm": "매봉",
  "line_num": "3",
  "station_cd": "0333"
}, {
  "station_nm": "무악재",
  "line_num": "3",
  "station_cd": "0315"
}, {
  "station_nm": "백석",
  "line_num": "3",
  "station_cd": "1954"
}, {
  "station_nm": "불광",
  "line_num": "3",
  "station_cd": "0312"
}, {
  "station_nm": "삼송",
  "line_num": "3",
  "station_cd": "1950"
}, {
  "station_nm": "수서",
  "line_num": "3",
  "station_cd": "0339"
}, {
  "station_nm": "신사",
  "line_num": "3",
  "station_cd": "0327"
}, {
  "station_nm": "안국",
  "line_num": "3",
  "station_cd": "0318"
}, {
  "station_nm": "압구정",
  "line_num": "3",
  "station_cd": "0326"
}, {
  "station_nm": "약수",
  "line_num": "3",
  "station_cd": "0323"
}, {
  "station_nm": "양재",
  "line_num": "3",
  "station_cd": "0332"
}, {
  "station_nm": "연신내",
  "line_num": "3",
  "station_cd": "0311"
}, {
  "station_nm": "오금",
  "line_num": "3",
  "station_cd": "0342"
}, {
  "station_nm": "옥수",
  "line_num": "3",
  "station_cd": "0325"
}, {
  "station_nm": "원당",
  "line_num": "3",
  "station_cd": "1951"
}, {
  "station_nm": "원흥",
  "line_num": "3",
  "station_cd": "1948"
}, {
  "station_nm": "을지로3가",
  "line_num": "3",
  "station_cd": "0320"
}, {
  "station_nm": "일원",
  "line_num": "3",
  "station_cd": "0338"
}, {
  "station_nm": "잠원",
  "line_num": "3",
  "station_cd": "0328"
}, {
  "station_nm": "정발산",
  "line_num": "3",
  "station_cd": "1956"
}, {
  "station_nm": "종로3가",
  "line_num": "3",
  "station_cd": "0319"
}, {
  "station_nm": "주엽",
  "line_num": "3",
  "station_cd": "1957"
}, {
  "station_nm": "지축",
  "line_num": "3",
  "station_cd": "0309"
}, {
  "station_nm": "충무로",
  "line_num": "3",
  "station_cd": "0321"
}, {
  "station_nm": "학여울",
  "line_num": "3",
  "station_cd": "0336"
}, {
  "station_nm": "홍제",
  "line_num": "3",
  "station_cd": "0314"
}, {
  "station_nm": "화정",
  "line_num": "3",
  "station_cd": "1952"
}, {
  "station_nm": "경마공원",
  "line_num": "4",
  "station_cd": "1451"
}, {
  "station_nm": "고잔",
  "line_num": "4",
  "station_cd": "1757"
}, {
  "station_nm": "과천",
  "line_num": "4",
  "station_cd": "1453"
}, {
  "station_nm": "금정",
  "line_num": "4",
  "station_cd": "1458"
}, {
  "station_nm": "길음",
  "line_num": "4",
  "station_cd": "0417"
}, {
  "station_nm": "남태령",
  "line_num": "4",
  "station_cd": "0434"
}, {
  "station_nm": "노원",
  "line_num": "4",
  "station_cd": "0411"
}, {
  "station_nm": "당고개",
  "line_num": "4",
  "station_cd": "0409"
}, {
  "station_nm": "대공원",
  "line_num": "4",
  "station_cd": "1452"
}, {
  "station_nm": "대야미",
  "line_num": "4",
  "station_cd": "1752"
}, {
  "station_nm": "동대문",
  "line_num": "4",
  "station_cd": "0421"
}, {
  "station_nm": "동대문역사문화공원",
  "line_num": "4",
  "station_cd": "0422"
}, {
  "station_nm": "동작",
  "line_num": "4",
  "station_cd": "0431"
}, {
  "station_nm": "명동",
  "line_num": "4",
  "station_cd": "0424"
}, {
  "station_nm": "미아",
  "line_num": "4",
  "station_cd": "0415"
}, {
  "station_nm": "미아사거리",
  "line_num": "4",
  "station_cd": "0416"
}, {
  "station_nm": "반월",
  "line_num": "4",
  "station_cd": "1753"
}, {
  "station_nm": "범계",
  "line_num": "4",
  "station_cd": "1457"
}, {
  "station_nm": "사당",
  "line_num": "4",
  "station_cd": "0433"
}, {
  "station_nm": "산본",
  "line_num": "4",
  "station_cd": "1751"
}, {
  "station_nm": "삼각지",
  "line_num": "4",
  "station_cd": "0428"
}, {
  "station_nm": "상계",
  "line_num": "4",
  "station_cd": "0410"
}, {
  "station_nm": "상록수",
  "line_num": "4",
  "station_cd": "1754"
}, {
  "station_nm": "서울",
  "line_num": "4",
  "station_cd": "0426"
}, {
  "station_nm": "선바위",
  "line_num": "4",
  "station_cd": "1450"
}, {
  "station_nm": "성신여대입구",
  "line_num": "4",
  "station_cd": "0418"
}, {
  "station_nm": "수리산",
  "line_num": "4",
  "station_cd": "1763"
}, {
  "station_nm": "수유",
  "line_num": "4",
  "station_cd": "0414"
}, {
  "station_nm": "숙대입구",
  "line_num": "4",
  "station_cd": "0427"
}, {
  "station_nm": "신길온천",
  "line_num": "4",
  "station_cd": "1760"
}, {
  "station_nm": "신용산",
  "line_num": "4",
  "station_cd": "0429"
}, {
  "station_nm": "쌍문",
  "line_num": "4",
  "station_cd": "0413"
}, {
  "station_nm": "안산",
  "line_num": "4",
  "station_cd": "1759"
}, {
  "station_nm": "오이도",
  "line_num": "4",
  "station_cd": "1762"
}, {
  "station_nm": "이촌",
  "line_num": "4",
  "station_cd": "0430"
}, {
  "station_nm": "인덕원",
  "line_num": "4",
  "station_cd": "1455"
}, {
  "station_nm": "정부과천청사",
  "line_num": "4",
  "station_cd": "1454"
}, {
  "station_nm": "정왕",
  "line_num": "4",
  "station_cd": "1761"
}, {
  "station_nm": "중앙",
  "line_num": "4",
  "station_cd": "1756"
}, {
  "station_nm": "창동",
  "line_num": "4",
  "station_cd": "0412"
}, {
  "station_nm": "초지",
  "line_num": "4",
  "station_cd": "1758"
}, {
  "station_nm": "총신대입구(이수)",
  "line_num": "4",
  "station_cd": "0432"
}, {
  "station_nm": "충무로",
  "line_num": "4",
  "station_cd": "0423"
}, {
  "station_nm": "평촌",
  "line_num": "4",
  "station_cd": "1456"
}, {
  "station_nm": "한대앞",
  "line_num": "4",
  "station_cd": "1755"
}, {
  "station_nm": "한성대입구",
  "line_num": "4",
  "station_cd": "0419"
}, {
  "station_nm": "혜화",
  "line_num": "4",
  "station_cd": "0420"
}, {
  "station_nm": "회현",
  "line_num": "4",
  "station_cd": "0425"
}, {
  "station_nm": "강동",
  "line_num": "5",
  "station_cd": "2549"
}, {
  "station_nm": "개롱",
  "line_num": "5",
  "station_cd": "2559"
}, {
  "station_nm": "개화산",
  "line_num": "5",
  "station_cd": "2512"
}, {
  "station_nm": "거여",
  "line_num": "5",
  "station_cd": "2560"
}, {
  "station_nm": "고덕",
  "line_num": "5",
  "station_cd": "2553"
}, {
  "station_nm": "공덕",
  "line_num": "5",
  "station_cd": "2530"
}, {
  "station_nm": "광나루",
  "line_num": "5",
  "station_cd": "2547"
}, {
  "station_nm": "광화문",
  "line_num": "5",
  "station_cd": "2534"
}, {
  "station_nm": "군자",
  "line_num": "5",
  "station_cd": "2545"
}, {
  "station_nm": "굽은다리",
  "line_num": "5",
  "station_cd": "2551"
}, {
  "station_nm": "길동",
  "line_num": "5",
  "station_cd": "2550"
}, {
  "station_nm": "김포공항",
  "line_num": "5",
  "station_cd": "2513"
}, {
  "station_nm": "까치산",
  "line_num": "5",
  "station_cd": "2519"
}, {
  "station_nm": "답십리",
  "line_num": "5",
  "station_cd": "2543"
}, {
  "station_nm": "동대문역사문화공원",
  "line_num": "5",
  "station_cd": "2537"
}, {
  "station_nm": "둔촌동",
  "line_num": "5",
  "station_cd": "2555"
}, {
  "station_nm": "마곡",
  "line_num": "5",
  "station_cd": "2515"
}, {
  "station_nm": "마장",
  "line_num": "5",
  "station_cd": "2542"
}, {
  "station_nm": "마천",
  "line_num": "5",
  "station_cd": "2561"
}, {
  "station_nm": "마포",
  "line_num": "5",
  "station_cd": "2529"
}, {
  "station_nm": "명일",
  "line_num": "5",
  "station_cd": "2552"
}, {
  "station_nm": "목동",
  "line_num": "5",
  "station_cd": "2521"
}, {
  "station_nm": "발산",
  "line_num": "5",
  "station_cd": "2516"
}, {
  "station_nm": "방이",
  "line_num": "5",
  "station_cd": "2557"
}, {
  "station_nm": "방화",
  "line_num": "5",
  "station_cd": "2511"
}, {
  "station_nm": "상일동",
  "line_num": "5",
  "station_cd": "2554"
}, {
  "station_nm": "서대문",
  "line_num": "5",
  "station_cd": "2533"
}, {
  "station_nm": "송정",
  "line_num": "5",
  "station_cd": "2514"
}, {
  "station_nm": "신금호",
  "line_num": "5",
  "station_cd": "2539"
}, {
  "station_nm": "신길",
  "line_num": "5",
  "station_cd": "2526"
}, {
  "station_nm": "신정",
  "line_num": "5",
  "station_cd": "2520"
}, {
  "station_nm": "아차산",
  "line_num": "5",
  "station_cd": "2546"
}, {
  "station_nm": "애오개",
  "line_num": "5",
  "station_cd": "2531"
}, {
  "station_nm": "양평",
  "line_num": "5",
  "station_cd": "2523"
}, {
  "station_nm": "여의나루",
  "line_num": "5",
  "station_cd": "2528"
}, {
  "station_nm": "여의도",
  "line_num": "5",
  "station_cd": "2527"
}, {
  "station_nm": "영등포구청",
  "line_num": "5",
  "station_cd": "2524"
}, {
  "station_nm": "영등포시장",
  "line_num": "5",
  "station_cd": "2525"
}, {
  "station_nm": "오금",
  "line_num": "5",
  "station_cd": "2558"
}, {
  "station_nm": "오목교",
  "line_num": "5",
  "station_cd": "2522"
}, {
  "station_nm": "올림픽공원",
  "line_num": "5",
  "station_cd": "2556"
}, {
  "station_nm": "왕십리",
  "line_num": "5",
  "station_cd": "2541"
}, {
  "station_nm": "우장산",
  "line_num": "5",
  "station_cd": "2517"
}, {
  "station_nm": "을지로4가",
  "line_num": "5",
  "station_cd": "2536"
}, {
  "station_nm": "장한평",
  "line_num": "5",
  "station_cd": "2544"
}, {
  "station_nm": "종로3가",
  "line_num": "5",
  "station_cd": "2535"
}, {
  "station_nm": "천호",
  "line_num": "5",
  "station_cd": "2548"
}, {
  "station_nm": "청구",
  "line_num": "5",
  "station_cd": "2538"
}, {
  "station_nm": "충정로",
  "line_num": "5",
  "station_cd": "2532"
}, {
  "station_nm": "행당",
  "line_num": "5",
  "station_cd": "2540"
}, {
  "station_nm": "화곡",
  "line_num": "5",
  "station_cd": "2518"
}, {
  "station_nm": "고려대",
  "line_num": "6",
  "station_cd": "2641"
}, {
  "station_nm": "공덕",
  "line_num": "6",
  "station_cd": "2627"
}, {
  "station_nm": "광흥창",
  "line_num": "6",
  "station_cd": "2625"
}, {
  "station_nm": "구산",
  "line_num": "6",
  "station_cd": "2616"
}, {
  "station_nm": "녹사평",
  "line_num": "6",
  "station_cd": "2630"
}, {
  "station_nm": "대흥",
  "line_num": "6",
  "station_cd": "2626"
}, {
  "station_nm": "독바위",
  "line_num": "6",
  "station_cd": "2614"
}, {
  "station_nm": "돌곶이",
  "line_num": "6",
  "station_cd": "2644"
}, {
  "station_nm": "동묘앞",
  "line_num": "6",
  "station_cd": "2637"
}, {
  "station_nm": "디지털미디어시티",
  "line_num": "6",
  "station_cd": "2619"
}, {
  "station_nm": "마포구청",
  "line_num": "6",
  "station_cd": "2621"
}, {
  "station_nm": "망원",
  "line_num": "6",
  "station_cd": "2622"
}, {
  "station_nm": "버티고개",
  "line_num": "6",
  "station_cd": "2633"
}, {
  "station_nm": "보문",
  "line_num": "6",
  "station_cd": "2639"
}, {
  "station_nm": "봉화산",
  "line_num": "6",
  "station_cd": "2648"
}, {
  "station_nm": "불광",
  "line_num": "6",
  "station_cd": "2613"
}, {
  "station_nm": "삼각지",
  "line_num": "6",
  "station_cd": "2629"
}, {
  "station_nm": "상수",
  "line_num": "6",
  "station_cd": "2624"
}, {
  "station_nm": "상월곡",
  "line_num": "6",
  "station_cd": "2643"
}, {
  "station_nm": "새절",
  "line_num": "6",
  "station_cd": "2617"
}, {
  "station_nm": "석계",
  "line_num": "6",
  "station_cd": "2645"
}, {
  "station_nm": "신당",
  "line_num": "6",
  "station_cd": "2636"
}, {
  "station_nm": "안암",
  "line_num": "6",
  "station_cd": "2640"
}, {
  "station_nm": "약수",
  "line_num": "6",
  "station_cd": "2634"
}, {
  "station_nm": "역촌",
  "line_num": "6",
  "station_cd": "2612"
}, {
  "station_nm": "연신내",
  "line_num": "6",
  "station_cd": "2615"
}, {
  "station_nm": "월곡",
  "line_num": "6",
  "station_cd": "2642"
}, {
  "station_nm": "월드컵경기장",
  "line_num": "6",
  "station_cd": "2620"
}, {
  "station_nm": "응암",
  "line_num": "6",
  "station_cd": "2611"
}, {
  "station_nm": "이태원",
  "line_num": "6",
  "station_cd": "2631"
}, {
  "station_nm": "증산",
  "line_num": "6",
  "station_cd": "2618"
}, {
  "station_nm": "창신",
  "line_num": "6",
  "station_cd": "2638"
}, {
  "station_nm": "청구",
  "line_num": "6",
  "station_cd": "2635"
}, {
  "station_nm": "태릉입구",
  "line_num": "6",
  "station_cd": "2646"
}, {
  "station_nm": "한강진",
  "line_num": "6",
  "station_cd": "2632"
}, {
  "station_nm": "합정",
  "line_num": "6",
  "station_cd": "2623"
}, {
  "station_nm": "화랑대",
  "line_num": "6",
  "station_cd": "2647"
}, {
  "station_nm": "효창공원앞",
  "line_num": "6",
  "station_cd": "2628"
}, {
  "station_nm": "가산디지털단지",
  "line_num": "7",
  "station_cd": "2748"
}, {
  "station_nm": "강남구청",
  "line_num": "7",
  "station_cd": "2732"
}, {
  "station_nm": "건대입구",
  "line_num": "7",
  "station_cd": "2729"
}, {
  "station_nm": "고속터미널",
  "line_num": "7",
  "station_cd": "2736"
}, {
  "station_nm": "공릉",
  "line_num": "7",
  "station_cd": "2718"
}, {
  "station_nm": "광명사거리",
  "line_num": "7",
  "station_cd": "2750"
}, {
  "station_nm": "군자",
  "line_num": "7",
  "station_cd": "2727"
}, {
  "station_nm": "굴포천",
  "line_num": "7",
  "station_cd": "2760"
}, {
  "station_nm": "까치울",
  "line_num": "7",
  "station_cd": "2753"
}, {
  "station_nm": "남구로",
  "line_num": "7",
  "station_cd": "2747"
}, {
  "station_nm": "남성",
  "line_num": "7",
  "station_cd": "2739"
}, {
  "station_nm": "내방",
  "line_num": "7",
  "station_cd": "2737"
}, {
  "station_nm": "노원",
  "line_num": "7",
  "station_cd": "2715"
}, {
  "station_nm": "논현",
  "line_num": "7",
  "station_cd": "2734"
}, {
  "station_nm": "대림",
  "line_num": "7",
  "station_cd": "2746"
}, {
  "station_nm": "도봉산",
  "line_num": "7",
  "station_cd": "2712"
}, {
  "station_nm": "뚝섬유원지",
  "line_num": "7",
  "station_cd": "2730"
}, {
  "station_nm": "마들",
  "line_num": "7",
  "station_cd": "2714"
}, {
  "station_nm": "먹골",
  "line_num": "7",
  "station_cd": "2720"
}, {
  "station_nm": "면목",
  "line_num": "7",
  "station_cd": "2723"
}, {
  "station_nm": "반포",
  "line_num": "7",
  "station_cd": "2735"
}, {
  "station_nm": "보라매",
  "line_num": "7",
  "station_cd": "2744"
}, {
  "station_nm": "부천시청",
  "line_num": "7",
  "station_cd": "2757"
}, {
  "station_nm": "부천종합운동장",
  "line_num": "7",
  "station_cd": "2754"
}, {
  "station_nm": "부평구청",
  "line_num": "7",
  "station_cd": "2761"
}, {
  "station_nm": "사가정",
  "line_num": "7",
  "station_cd": "2724"
}, {
  "station_nm": "삼산체육관",
  "line_num": "7",
  "station_cd": "2759"
}, {
  "station_nm": "상도",
  "line_num": "7",
  "station_cd": "2741"
}, {
  "station_nm": "상동",
  "line_num": "7",
  "station_cd": "2758"
}, {
  "station_nm": "상봉",
  "line_num": "7",
  "station_cd": "2722"
}, {
  "station_nm": "수락산",
  "line_num": "7",
  "station_cd": "2713"
}, {
  "station_nm": "숭실대입구",
  "line_num": "7",
  "station_cd": "2740"
}, {
  "station_nm": "신대방삼거리",
  "line_num": "7",
  "station_cd": "2743"
}, {
  "station_nm": "신중동",
  "line_num": "7",
  "station_cd": "2756"
}, {
  "station_nm": "신풍",
  "line_num": "7",
  "station_cd": "2745"
}, {
  "station_nm": "어린이대공원",
  "line_num": "7",
  "station_cd": "2728"
}, {
  "station_nm": "온수",
  "line_num": "7",
  "station_cd": "2752"
}, {
  "station_nm": "용마산",
  "line_num": "7",
  "station_cd": "2725"
}, {
  "station_nm": "장승배기",
  "line_num": "7",
  "station_cd": "2742"
}, {
  "station_nm": "장암",
  "line_num": "7",
  "station_cd": "2711"
}, {
  "station_nm": "중계",
  "line_num": "7",
  "station_cd": "2716"
}, {
  "station_nm": "중곡",
  "line_num": "7",
  "station_cd": "2726"
}, {
  "station_nm": "중화",
  "line_num": "7",
  "station_cd": "2721"
}, {
  "station_nm": "천왕",
  "line_num": "7",
  "station_cd": "2751"
}, {
  "station_nm": "철산",
  "line_num": "7",
  "station_cd": "2749"
}, {
  "station_nm": "청담",
  "line_num": "7",
  "station_cd": "2731"
}, {
  "station_nm": "총신대입구(이수)",
  "line_num": "7",
  "station_cd": "2738"
}, {
  "station_nm": "춘의",
  "line_num": "7",
  "station_cd": "2755"
}, {
  "station_nm": "태릉입구",
  "line_num": "7",
  "station_cd": "2719"
}, {
  "station_nm": "하계",
  "line_num": "7",
  "station_cd": "2717"
}, {
  "station_nm": "학동",
  "line_num": "7",
  "station_cd": "2733"
}, {
  "station_nm": "가락시장",
  "line_num": "8",
  "station_cd": "2818"
}, {
  "station_nm": "강동구청",
  "line_num": "8",
  "station_cd": "2813"
}, {
  "station_nm": "남한산성입구",
  "line_num": "8",
  "station_cd": "2823"
}, {
  "station_nm": "단대오거리",
  "line_num": "8",
  "station_cd": "2824"
}, {
  "station_nm": "모란",
  "line_num": "8",
  "station_cd": "2827"
}, {
  "station_nm": "몽촌토성",
  "line_num": "8",
  "station_cd": "2814"
}, {
  "station_nm": "문정",
  "line_num": "8",
  "station_cd": "2819"
}, {
  "station_nm": "복정",
  "line_num": "8",
  "station_cd": "2821"
}, {
  "station_nm": "산성",
  "line_num": "8",
  "station_cd": "2822"
}, {
  "station_nm": "석촌",
  "line_num": "8",
  "station_cd": "2816"
}, {
  "station_nm": "송파",
  "line_num": "8",
  "station_cd": "2817"
}, {
  "station_nm": "수진",
  "line_num": "8",
  "station_cd": "2826"
}, {
  "station_nm": "신흥",
  "line_num": "8",
  "station_cd": "2825"
}, {
  "station_nm": "암사",
  "line_num": "8",
  "station_cd": "2811"
}, {
  "station_nm": "잠실",
  "line_num": "8",
  "station_cd": "2815"
}, {
  "station_nm": "장지",
  "line_num": "8",
  "station_cd": "2820"
}, {
  "station_nm": "천호",
  "line_num": "8",
  "station_cd": "2812"
}, {
  "station_nm": "가양",
  "line_num": "9",
  "station_cd": "4107"
}, {
  "station_nm": "개화",
  "line_num": "9",
  "station_cd": "4101"
}, {
  "station_nm": "고속터미널",
  "line_num": "9",
  "station_cd": "4123"
}, {
  "station_nm": "공항시장",
  "line_num": "9",
  "station_cd": "4103"
}, {
  "station_nm": "구반포",
  "line_num": "9",
  "station_cd": "4121"
}, {
  "station_nm": "국회의사당",
  "line_num": "9",
  "station_cd": "4114"
}, {
  "station_nm": "김포공항",
  "line_num": "9",
  "station_cd": "4102"
}, {
  "station_nm": "노들",
  "line_num": "9",
  "station_cd": "4118"
}, {
  "station_nm": "노량진",
  "line_num": "9",
  "station_cd": "4117"
}, {
  "station_nm": "당산",
  "line_num": "9",
  "station_cd": "4113"
}, {
  "station_nm": "동작",
  "line_num": "9",
  "station_cd": "4120"
}, {
  "station_nm": "등촌",
  "line_num": "9",
  "station_cd": "4109"
}, {
  "station_nm": "마곡나루",
  "line_num": "9",
  "station_cd": "4105"
}, {
  "station_nm": "봉은사",
  "line_num": "9",
  "station_cd": "4129"
}, {
  "station_nm": "사평",
  "line_num": "9",
  "station_cd": "4124"
}, {
  "station_nm": "삼성중앙",
  "line_num": "9",
  "station_cd": "4128"
}, {
  "station_nm": "샛강",
  "line_num": "9",
  "station_cd": "4116"
}, {
  "station_nm": "선유도",
  "line_num": "9",
  "station_cd": "4112"
}, {
  "station_nm": "선정릉",
  "line_num": "9",
  "station_cd": "4127"
}, {
  "station_nm": "신논현",
  "line_num": "9",
  "station_cd": "4125"
}, {
  "station_nm": "신목동",
  "line_num": "9",
  "station_cd": "4111"
}, {
  "station_nm": "신반포",
  "line_num": "9",
  "station_cd": "4122"
}, {
  "station_nm": "신방화",
  "line_num": "9",
  "station_cd": "4104"
}, {
  "station_nm": "양천향교",
  "line_num": "9",
  "station_cd": "4106"
}, {
  "station_nm": "언주",
  "line_num": "9",
  "station_cd": "4126"
}, {
  "station_nm": "여의도",
  "line_num": "9",
  "station_cd": "4115"
}, {
  "station_nm": "염창",
  "line_num": "9",
  "station_cd": "4110"
}, {
  "station_nm": "종합운동장",
  "line_num": "9",
  "station_cd": "4130"
}, {
  "station_nm": "증미",
  "line_num": "9",
  "station_cd": "4108"
}, {
  "station_nm": "흑석",
  "line_num": "9",
  "station_cd": "4119"
}, {
  "station_nm": "검암",
  "line_num": "A",
  "station_cd": "4209"
}, {
  "station_nm": "계양",
  "line_num": "A",
  "station_cd": "4208"
}, {
  "station_nm": "공덕",
  "line_num": "A",
  "station_cd": "4202"
}, {
  "station_nm": "공항화물청사",
  "line_num": "A",
  "station_cd": "4212"
}, {
  "station_nm": "김포공항",
  "line_num": "A",
  "station_cd": "4207"
}, {
  "station_nm": "디지털미디어시티",
  "line_num": "A",
  "station_cd": "4204"
}, {
  "station_nm": "서울",
  "line_num": "A",
  "station_cd": "4201"
}, {
  "station_nm": "영종",
  "line_num": "A",
  "station_cd": "4217"
}, {
  "station_nm": "운서",
  "line_num": "A",
  "station_cd": "4211"
}, {
  "station_nm": "인천공항1터미널",
  "line_num": "A",
  "station_cd": "4213"
}, {
  "station_nm": "인천공항2터미널",
  "line_num": "A",
  "station_cd": "4215"
}, {
  "station_nm": "청라국제도시",
  "line_num": "A",
  "station_cd": "4210"
}, {
  "station_nm": "홍대입구",
  "line_num": "A",
  "station_cd": "4203"
}, {
  "station_nm": "가천대",
  "line_num": "B",
  "station_cd": "1851"
}, {
  "station_nm": "강남구청",
  "line_num": "B",
  "station_cd": "1849"
}, {
  "station_nm": "개포동",
  "line_num": "B",
  "station_cd": "1027"
}, {
  "station_nm": "구룡",
  "line_num": "B",
  "station_cd": "1026"
}, {
  "station_nm": "구성",
  "line_num": "B",
  "station_cd": "1863"
}, {
  "station_nm": "기흥",
  "line_num": "B",
  "station_cd": "1865"
}, {
  "station_nm": "대모산입구",
  "line_num": "B",
  "station_cd": "1028"
}, {
  "station_nm": "도곡",
  "line_num": "B",
  "station_cd": "1025"
}, {
  "station_nm": "망포",
  "line_num": "B",
  "station_cd": "1869"
}, {
  "station_nm": "매교",
  "line_num": "B",
  "station_cd": "1872"
}, {
  "station_nm": "매탄권선",
  "line_num": "B",
  "station_cd": "1870"
}, {
  "station_nm": "모란",
  "line_num": "B",
  "station_cd": "1853"
}, {
  "station_nm": "미금",
  "line_num": "B",
  "station_cd": "1858"
}, {
  "station_nm": "보정",
  "line_num": "B",
  "station_cd": "1861"
}, {
  "station_nm": "복정",
  "line_num": "B",
  "station_cd": "1031"
}, {
  "station_nm": "상갈",
  "line_num": "B",
  "station_cd": "1866"
}, {
  "station_nm": "서울숲",
  "line_num": "B",
  "station_cd": "1847"
}, {
  "station_nm": "서현",
  "line_num": "B",
  "station_cd": "1855"
}, {
  "station_nm": "선릉",
  "line_num": "B",
  "station_cd": "1023"
}, {
  "station_nm": "선정릉",
  "line_num": "B",
  "station_cd": "1850"
}, {
  "station_nm": "수내",
  "line_num": "B",
  "station_cd": "1856"
}, {
  "station_nm": "수서",
  "line_num": "B",
  "station_cd": "1030"
}, {
  "station_nm": "수원",
  "line_num": "B",
  "station_cd": "1846"
}, {
  "station_nm": "수원시청",
  "line_num": "B",
  "station_cd": "1871"
}, {
  "station_nm": "신갈",
  "line_num": "B",
  "station_cd": "1864"
}, {
  "station_nm": "압구정로데오",
  "line_num": "B",
  "station_cd": "1848"
}, {
  "station_nm": "야탑",
  "line_num": "B",
  "station_cd": "1854"
}, {
  "station_nm": "영통",
  "line_num": "B",
  "station_cd": "1868"
}, {
  "station_nm": "오리",
  "line_num": "B",
  "station_cd": "1859"
}, {
  "station_nm": "왕십리",
  "line_num": "B",
  "station_cd": "102C"
}, {
  "station_nm": "이매",
  "line_num": "B",
  "station_cd": "1860"
}, {
  "station_nm": "정자",
  "line_num": "B",
  "station_cd": "1857"
}, {
  "station_nm": "죽전",
  "line_num": "B",
  "station_cd": "1862"
}, {
  "station_nm": "청명",
  "line_num": "B",
  "station_cd": "1867"
}, {
  "station_nm": "태평",
  "line_num": "B",
  "station_cd": "1852"
}, {
  "station_nm": "한티",
  "line_num": "B",
  "station_cd": "1024"
}, {
  "station_nm": "강남대",
  "line_num": "E",
  "station_cd": "4502"
}, {
  "station_nm": "고진",
  "line_num": "E",
  "station_cd": "4513"
}, {
  "station_nm": "기흥",
  "line_num": "E",
  "station_cd": "4501"
}, {
  "station_nm": "김량장",
  "line_num": "E",
  "station_cd": "4511"
}, {
  "station_nm": "동백",
  "line_num": "E",
  "station_cd": "4505"
}, {
  "station_nm": "둔전",
  "line_num": "E",
  "station_cd": "4515"
}, {
  "station_nm": "명지대",
  "line_num": "E",
  "station_cd": "4510"
}, {
  "station_nm": "보평",
  "line_num": "E",
  "station_cd": "4514"
}, {
  "station_nm": "삼가",
  "line_num": "E",
  "station_cd": "4508"
}, {
  "station_nm": "시청·용인대",
  "line_num": "E",
  "station_cd": "4509"
}, {
  "station_nm": "어정",
  "line_num": "E",
  "station_cd": "4504"
}, {
  "station_nm": "운동장·송담대",
  "line_num": "E",
  "station_cd": "4512"
}, {
  "station_nm": "전대·에버랜드",
  "line_num": "E",
  "station_cd": "4517"
}, {
  "station_nm": "지석",
  "line_num": "E",
  "station_cd": "4503"
}, {
  "station_nm": "초당",
  "line_num": "E",
  "station_cd": "4506"
}, {
  "station_nm": "가평",
  "line_num": "G",
  "station_cd": "1323"
}, {
  "station_nm": "갈매",
  "line_num": "G",
  "station_cd": "1312"
}, {
  "station_nm": "강촌",
  "line_num": "G",
  "station_cd": "1326"
}, {
  "station_nm": "광운대",
  "line_num": "G",
  "station_cd": "1305"
}, {
  "station_nm": "굴봉산",
  "line_num": "G",
  "station_cd": "1324"
}, {
  "station_nm": "금곡",
  "line_num": "G",
  "station_cd": "1316"
}, {
  "station_nm": "김유정",
  "line_num": "G",
  "station_cd": "1327"
}, {
  "station_nm": "남춘천",
  "line_num": "G",
  "station_cd": "1328"
}, {
  "station_nm": "대성리",
  "line_num": "G",
  "station_cd": "1320"
}, {
  "station_nm": "마석",
  "line_num": "G",
  "station_cd": "1319"
}, {
  "station_nm": "망우",
  "line_num": "G",
  "station_cd": "1310"
}, {
  "station_nm": "백양리",
  "line_num": "G",
  "station_cd": "1325"
}, {
  "station_nm": "별내",
  "line_num": "G",
  "station_cd": "1313"
}, {
  "station_nm": "사릉",
  "line_num": "G",
  "station_cd": "1315"
}, {
  "station_nm": "상봉",
  "line_num": "G",
  "station_cd": "1309"
}, {
  "station_nm": "상천",
  "line_num": "G",
  "station_cd": "1322"
}, {
  "station_nm": "신내",
  "line_num": "G",
  "station_cd": "1311"
}, {
  "station_nm": "중랑",
  "line_num": "G",
  "station_cd": "1308"
}, {
  "station_nm": "천마산",
  "line_num": "G",
  "station_cd": "1318"
}, {
  "station_nm": "청량리",
  "line_num": "G",
  "station_cd": "1306"
}, {
  "station_nm": "청평",
  "line_num": "G",
  "station_cd": "1321"
}, {
  "station_nm": "춘천",
  "line_num": "G",
  "station_cd": "1329"
}, {
  "station_nm": "퇴계원",
  "line_num": "G",
  "station_cd": "1314"
}, {
  "station_nm": "평내호평",
  "line_num": "G",
  "station_cd": "1317"
}, {
  "station_nm": "회기",
  "line_num": "G",
  "station_cd": "1307"
}, {
  "station_nm": "간석오거리",
  "line_num": "I",
  "station_cd": "3123"
}, {
  "station_nm": "갈산",
  "line_num": "I",
  "station_cd": "3117"
}, {
  "station_nm": "경인교대입구",
  "line_num": "I",
  "station_cd": "3115"
}, {
  "station_nm": "계산",
  "line_num": "I",
  "station_cd": "3114"
}, {
  "station_nm": "계양",
  "line_num": "I",
  "station_cd": "3110"
}, {
  "station_nm": "국제업무지구",
  "line_num": "I",
  "station_cd": "3138"
}, {
  "station_nm": "귤현",
  "line_num": "I",
  "station_cd": "3111"
}, {
  "station_nm": "동막",
  "line_num": "I",
  "station_cd": "3132"
}, {
  "station_nm": "동수",
  "line_num": "I",
  "station_cd": "3121"
}, {
  "station_nm": "동춘",
  "line_num": "I",
  "station_cd": "3131"
}, {
  "station_nm": "문학경기장",
  "line_num": "I",
  "station_cd": "3127"
}, {
  "station_nm": "박촌",
  "line_num": "I",
  "station_cd": "3112"
}, {
  "station_nm": "부평",
  "line_num": "I",
  "station_cd": "3120"
}, {
  "station_nm": "부평구청",
  "line_num": "I",
  "station_cd": "3118"
}, {
  "station_nm": "부평삼거리",
  "line_num": "I",
  "station_cd": "3122"
}, {
  "station_nm": "부평시장",
  "line_num": "I",
  "station_cd": "3119"
}, {
  "station_nm": "선학",
  "line_num": "I",
  "station_cd": "3128"
}, {
  "station_nm": "센트럴파크",
  "line_num": "I",
  "station_cd": "3137"
}, {
  "station_nm": "신연수",
  "line_num": "I",
  "station_cd": "3129"
}, {
  "station_nm": "예술회관",
  "line_num": "I",
  "station_cd": "3125"
}, {
  "station_nm": "원인재",
  "line_num": "I",
  "station_cd": "3130"
}, {
  "station_nm": "인천대입구",
  "line_num": "I",
  "station_cd": "3136"
}, {
  "station_nm": "인천시청",
  "line_num": "I",
  "station_cd": "3124"
}, {
  "station_nm": "인천터미널",
  "line_num": "I",
  "station_cd": "3126"
}, {
  "station_nm": "임학",
  "line_num": "I",
  "station_cd": "3113"
}, {
  "station_nm": "작전",
  "line_num": "I",
  "station_cd": "3116"
}, {
  "station_nm": "지식정보단지",
  "line_num": "I",
  "station_cd": "3135"
}, {
  "station_nm": "캠퍼스타운",
  "line_num": "I",
  "station_cd": "3133"
}, {
  "station_nm": "테크노파크",
  "line_num": "I",
  "station_cd": "3134"
}, {
  "station_nm": "가재울",
  "line_num": "I2",
  "station_cd": "3216"
}, {
  "station_nm": "가정",
  "line_num": "I2",
  "station_cd": "3211"
}, {
  "station_nm": "가정중앙시장",
  "line_num": "I2",
  "station_cd": "3212"
}, {
  "station_nm": "검단사거리",
  "line_num": "I2",
  "station_cd": "3203"
}, {
  "station_nm": "검단오류",
  "line_num": "I2",
  "station_cd": "3201"
}, {
  "station_nm": "검바위",
  "line_num": "I2",
  "station_cd": "3208"
}, {
  "station_nm": "검암",
  "line_num": "I2",
  "station_cd": "3207"
}, {
  "station_nm": "남동구청",
  "line_num": "I2",
  "station_cd": "3225"
}, {
  "station_nm": "독정",
  "line_num": "I2",
  "station_cd": "3206"
}, {
  "station_nm": "마전",
  "line_num": "I2",
  "station_cd": "3204"
}, {
  "station_nm": "만수",
  "line_num": "I2",
  "station_cd": "3224"
}, {
  "station_nm": "모래내시장",
  "line_num": "I2",
  "station_cd": "3223"
}, {
  "station_nm": "서구청",
  "line_num": "I2",
  "station_cd": "3210"
}, {
  "station_nm": "서부여성회관",
  "line_num": "I2",
  "station_cd": "3214"
}, {
  "station_nm": "석남",
  "line_num": "I2",
  "station_cd": "3213"
}, {
  "station_nm": "석바위시장",
  "line_num": "I2",
  "station_cd": "3220"
}, {
  "station_nm": "석천사거리",
  "line_num": "I2",
  "station_cd": "3222"
}, {
  "station_nm": "시민공원",
  "line_num": "I2",
  "station_cd": "3219"
}, {
  "station_nm": "아시아드경기장",
  "line_num": "I2",
  "station_cd": "3209"
}, {
  "station_nm": "완정",
  "line_num": "I2",
  "station_cd": "3205"
}, {
  "station_nm": "왕길",
  "line_num": "I2",
  "station_cd": "3202"
}, {
  "station_nm": "운연",
  "line_num": "I2",
  "station_cd": "3227"
}, {
  "station_nm": "인천가좌",
  "line_num": "I2",
  "station_cd": "3215"
}, {
  "station_nm": "인천대공원",
  "line_num": "I2",
  "station_cd": "3226"
}, {
  "station_nm": "인천시청",
  "line_num": "I2",
  "station_cd": "3221"
}, {
  "station_nm": "주안",
  "line_num": "I2",
  "station_cd": "3218"
}, {
  "station_nm": "주안국가산단",
  "line_num": "I2",
  "station_cd": "3217"
}, {
  "station_nm": "가좌",
  "line_num": "K",
  "station_cd": "1265"
}, {
  "station_nm": "강매",
  "line_num": "K",
  "station_cd": "1269"
}, {
  "station_nm": "곡산",
  "line_num": "K",
  "station_cd": "1272"
}, {
  "station_nm": "공덕",
  "line_num": "K",
  "station_cd": "1262"
}, {
  "station_nm": "구리",
  "line_num": "K",
  "station_cd": "1205"
}, {
  "station_nm": "국수",
  "line_num": "K",
  "station_cd": "1214"
}, {
  "station_nm": "금릉",
  "line_num": "K",
  "station_cd": "1279"
}, {
  "station_nm": "금촌",
  "line_num": "K",
  "station_cd": "1280"
}, {
  "station_nm": "능곡",
  "line_num": "K",
  "station_cd": "1271"
}, {
  "station_nm": "대곡",
  "line_num": "K",
  "station_cd": "0300"
}, {
  "station_nm": "덕소",
  "line_num": "K",
  "station_cd": "1208"
}, {
  "station_nm": "도농",
  "line_num": "K",
  "station_cd": "1206"
}, {
  "station_nm": "도심",
  "line_num": "K",
  "station_cd": "1209"
}, {
  "station_nm": "디지털미디어시티",
  "line_num": "K",
  "station_cd": "1266"
}, {
  "station_nm": "망우",
  "line_num": "K",
  "station_cd": "1203"
}, {
  "station_nm": "문산",
  "line_num": "K",
  "station_cd": "1284"
}, {
  "station_nm": "백마",
  "line_num": "K",
  "station_cd": "1273"
}, {
  "station_nm": "상봉",
  "line_num": "K",
  "station_cd": "1202"
}, {
  "station_nm": "서강대",
  "line_num": "K",
  "station_cd": "1263"
}, {
  "station_nm": "서빙고",
  "line_num": "K",
  "station_cd": "1009"
}, {
  "station_nm": "서울",
  "line_num": "K",
  "station_cd": "1251"
}, {
  "station_nm": "수색",
  "line_num": "K",
  "station_cd": "1267"
}, {
  "station_nm": "신원",
  "line_num": "K",
  "station_cd": "1213"
}, {
  "station_nm": "신촌(경의중앙선)",
  "line_num": "K",
  "station_cd": "1252"
}, {
  "station_nm": "아신",
  "line_num": "K",
  "station_cd": "1215"
}, {
  "station_nm": "야당",
  "line_num": "K",
  "station_cd": "1277"
}, {
  "station_nm": "양수",
  "line_num": "K",
  "station_cd": "1212"
}, {
  "station_nm": "양원",
  "line_num": "K",
  "station_cd": "1204"
}, {
  "station_nm": "양정",
  "line_num": "K",
  "station_cd": "1207"
}, {
  "station_nm": "양평(경의중앙선)",
  "line_num": "K",
  "station_cd": "1217"
}, {
  "station_nm": "오빈",
  "line_num": "K",
  "station_cd": "1216"
}, {
  "station_nm": "옥수",
  "line_num": "K",
  "station_cd": "1011"
}, {
  "station_nm": "왕십리",
  "line_num": "K",
  "station_cd": "1013"
}, {
  "station_nm": "용문",
  "line_num": "K",
  "station_cd": "1219"
}, {
  "station_nm": "용산",
  "line_num": "K",
  "station_cd": "100C"
}, {
  "station_nm": "운길산",
  "line_num": "K",
  "station_cd": "1211"
}, {
  "station_nm": "운정",
  "line_num": "K",
  "station_cd": "1278"
}, {
  "station_nm": "원덕",
  "line_num": "K",
  "station_cd": "1218"
}, {
  "station_nm": "월롱",
  "line_num": "K",
  "station_cd": "1282"
}, {
  "station_nm": "응봉",
  "line_num": "K",
  "station_cd": "1012"
}, {
  "station_nm": "이촌",
  "line_num": "K",
  "station_cd": "1008"
}, {
  "station_nm": "일산",
  "line_num": "K",
  "station_cd": "1275"
}, {
  "station_nm": "중랑",
  "line_num": "K",
  "station_cd": "1201"
}, {
  "station_nm": "지평",
  "line_num": "K",
  "station_cd": "1220"
}, {
  "station_nm": "청량리",
  "line_num": "K",
  "station_cd": "1014"
}, {
  "station_nm": "탄현",
  "line_num": "K",
  "station_cd": "1276"
}, {
  "station_nm": "파주",
  "line_num": "K",
  "station_cd": "1283"
}, {
  "station_nm": "팔당",
  "line_num": "K",
  "station_cd": "1210"
}, {
  "station_nm": "풍산",
  "line_num": "K",
  "station_cd": "1274"
}, {
  "station_nm": "한남",
  "line_num": "K",
  "station_cd": "1010"
}, {
  "station_nm": "행신",
  "line_num": "K",
  "station_cd": "1270"
}, {
  "station_nm": "홍대입구",
  "line_num": "K",
  "station_cd": "1264"
}, {
  "station_nm": "화전",
  "line_num": "K",
  "station_cd": "1268"
}, {
  "station_nm": "회기",
  "line_num": "K",
  "station_cd": "101C"
}, {
  "station_nm": "효창공원앞",
  "line_num": "K",
  "station_cd": "1261"
}, {
  "station_nm": "경기광주",
  "line_num": "KK",
  "station_cd": "1504"
}, {
  "station_nm": "곤지암",
  "line_num": "KK",
  "station_cd": "1506"
}, {
  "station_nm": "부발",
  "line_num": "KK",
  "station_cd": "1509"
}, {
  "station_nm": "삼동",
  "line_num": "KK",
  "station_cd": "1503"
}, {
  "station_nm": "세종대왕릉",
  "line_num": "KK",
  "station_cd": "1510"
}, {
  "station_nm": "신둔도예촌",
  "line_num": "KK",
  "station_cd": "1507"
}, {
  "station_nm": "여주",
  "line_num": "KK",
  "station_cd": "1511"
}, {
  "station_nm": "이매",
  "line_num": "KK",
  "station_cd": "1502"
}, {
  "station_nm": "이천",
  "line_num": "KK",
  "station_cd": "1508"
}, {
  "station_nm": "초월",
  "line_num": "KK",
  "station_cd": "1505"
}, {
  "station_nm": "판교",
  "line_num": "KK",
  "station_cd": "1501"
}, {
  "station_nm": "용유",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "워터파크",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "인천공항1터미널",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "장기주차장",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "파라다이스시티",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "합동청사",
  "line_num": "M",
  "station_cd": null
}, {
  "station_nm": "강남",
  "line_num": "S",
  "station_cd": "4307"
}, {
  "station_nm": "광교",
  "line_num": "S",
  "station_cd": "4319"
}, {
  "station_nm": "광교중앙",
  "line_num": "S",
  "station_cd": "4318"
}, {
  "station_nm": "동천",
  "line_num": "S",
  "station_cd": "4314"
}, {
  "station_nm": "미금",
  "line_num": "S",
  "station_cd": "4313"
}, {
  "station_nm": "상현",
  "line_num": "S",
  "station_cd": "4317"
}, {
  "station_nm": "성복",
  "line_num": "S",
  "station_cd": "4316"
}, {
  "station_nm": "수지구청",
  "line_num": "S",
  "station_cd": "4315"
}, {
  "station_nm": "양재",
  "line_num": "S",
  "station_cd": "4308"
}, {
  "station_nm": "양재시민의숲",
  "line_num": "S",
  "station_cd": "4309"
}, {
  "station_nm": "정자",
  "line_num": "S",
  "station_cd": "4312"
}, {
  "station_nm": "청계산입구",
  "line_num": "S",
  "station_cd": "4310"
}, {
  "station_nm": "판교",
  "line_num": "S",
  "station_cd": "4311"
}, {
  "station_nm": "남동인더스파크",
  "line_num": "SU",
  "station_cd": "1883"
}, {
  "station_nm": "달월",
  "line_num": "SU",
  "station_cd": "1878"
}, {
  "station_nm": "소래포구",
  "line_num": "SU",
  "station_cd": "1880"
}, {
  "station_nm": "송도",
  "line_num": "SU",
  "station_cd": "1886"
}, {
  "station_nm": "숭의",
  "line_num": "SU",
  "station_cd": "1889"
}, {
  "station_nm": "신포",
  "line_num": "SU",
  "station_cd": "1890"
}, {
  "station_nm": "연수",
  "line_num": "SU",
  "station_cd": "1885"
}, {
  "station_nm": "오이도",
  "line_num": "SU",
  "station_cd": "1800"
}, {
  "station_nm": "원인재",
  "line_num": "SU",
  "station_cd": "1884"
}, {
  "station_nm": "월곶",
  "line_num": "SU",
  "station_cd": "1879"
}, {
  "station_nm": "인천",
  "line_num": "SU",
  "station_cd": "1891"
}, {
  "station_nm": "인천논현",
  "line_num": "SU",
  "station_cd": "1881"
}, {
  "station_nm": "인하대",
  "line_num": "SU",
  "station_cd": "1888"
}, {
  "station_nm": "호구포",
  "line_num": "SU",
  "station_cd": "1882"
}, {
  "station_nm": "경기도청북부청사",
  "line_num": "U",
  "station_cd": "4610"
}, {
  "station_nm": "경전철의정부",
  "line_num": "U",
  "station_cd": "4604"
}, {
  "station_nm": "곤제",
  "line_num": "U",
  "station_cd": "4612"
}, {
  "station_nm": "동오",
  "line_num": "U",
  "station_cd": "4608"
}, {
  "station_nm": "발곡",
  "line_num": "U",
  "station_cd": "4601"
}, {
  "station_nm": "범골",
  "line_num": "U",
  "station_cd": "4603"
}, {
  "station_nm": "새말",
  "line_num": "U",
  "station_cd": "4609"
}, {
  "station_nm": "송산",
  "line_num": "U",
  "station_cd": "4614"
}, {
  "station_nm": "어룡",
  "line_num": "U",
  "station_cd": "4613"
}, {
  "station_nm": "의정부시청",
  "line_num": "U",
  "station_cd": "4605"
}, {
  "station_nm": "의정부중앙",
  "line_num": "U",
  "station_cd": "4607"
}, {
  "station_nm": "탑석",
  "line_num": "U",
  "station_cd": "4615"
}, {
  "station_nm": "회룡",
  "line_num": "U",
  "station_cd": "4602"
}, {
  "station_nm": "효자",
  "line_num": "U",
  "station_cd": "4611"
}, {
  "station_nm": "흥선",
  "line_num": "U",
  "station_cd": "4606"
}, {
  "station_nm": "4·19민주묘지",
  "line_num": "UI",
  "station_cd": "4703"
}, {
  "station_nm": "가오리",
  "line_num": "UI",
  "station_cd": "4704"
}, {
  "station_nm": "보문",
  "line_num": "UI",
  "station_cd": "4712"
}, {
  "station_nm": "북한산보국문",
  "line_num": "UI",
  "station_cd": "4709"
}, {
  "station_nm": "북한산우이",
  "line_num": "UI",
  "station_cd": "4701"
}, {
  "station_nm": "삼양",
  "line_num": "UI",
  "station_cd": "4706"
}, {
  "station_nm": "삼양사거리",
  "line_num": "UI",
  "station_cd": "4707"
}, {
  "station_nm": "성신여대입구",
  "line_num": "UI",
  "station_cd": "4711"
}, {
  "station_nm": "솔밭공원",
  "line_num": "UI",
  "station_cd": "4702"
}, {
  "station_nm": "솔샘",
  "line_num": "UI",
  "station_cd": "4708"
}, {
  "station_nm": "신설동",
  "line_num": "UI",
  "station_cd": "4713"
}, {
  "station_nm": "정릉",
  "line_num": "UI",
  "station_cd": "4710"
}, {
  "station_nm": "화계",
  "line_num": "UI",
  "station_cd": "4705"
}, {
  "station_nm": "달미",
  "line_num": "W",
  "station_cd": "4811"
}, {
  "station_nm": "선부",
  "line_num": "W",
  "station_cd": "4812"
}, {
  "station_nm": "소사",
  "line_num": "W",
  "station_cd": "4804"
}, {
  "station_nm": "소새울",
  "line_num": "W",
  "station_cd": "4805"
}, {
  "station_nm": "시흥능곡",
  "line_num": "W",
  "station_cd": "4810"
}, {
  "station_nm": "시흥대야",
  "line_num": "W",
  "station_cd": "4806"
}, {
  "station_nm": "시흥시청",
  "line_num": "W",
  "station_cd": "4809"
}, {
  "station_nm": "신천",
  "line_num": "W",
  "station_cd": "4807"
}, {
  "station_nm": "신현",
  "line_num": "W",
  "station_cd": "4808"
}, {
  "station_nm": "원곡",
  "line_num": "W",
  "station_cd": "4814"
}, {
  "station_nm": "원시",
  "line_num": "W",
  "station_cd": "4815"
}, {
  "station_nm": "초지",
  "line_num": "W",
  "station_cd": "4813"
}]